language: node_js
node_js:
- '5'
services:
- mongodb
addons:
  code_climate:
    repo_token: 9751e6a53baa954764e85e36f4957abe39918473dd02bd2db34ea5c5a61936a1
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  on:
    tags: true
    branches: true
